language: python
python:
- '3.6'
sudo: false
cache: pip3
install:
- pip3 install -r requirements.txt
- pip3 install coverage
- pip3 install coveralls
script:
- pytest --cov=api
- coverage report
- coverage xml
- coveralls
before_script:
- psql -U nnmmzuxramdvkg -f Fast-food.sql


#- ./cc-test-reporter before-build"